/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LotteryRouteImport } from './routes/lottery'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as BetHistoryRouteImport } from './routes/bet-history'
import { Route as AviatorRouteImport } from './routes/aviator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUpdatesRouteImport } from './routes/admin.updates'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteryRoute = LotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const BetHistoryRoute = BetHistoryRouteImport.update({
  id: '/bet-history',
  path: '/bet-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AviatorRoute = AviatorRouteImport.update({
  id: '/aviator',
  path: '/aviator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesRoute = AdminUpdatesRouteImport.update({
  id: '/admin/updates',
  path: '/admin/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/admin/broadcast',
  path: '/admin/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviator': typeof AviatorRoute
  '/bet-history': typeof BetHistoryRoute
  '/casino': typeof CasinoRoute
  '/lottery': typeof LotteryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/slots': typeof SlotsRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRoute
  '/wallet': typeof WalletRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviator': typeof AviatorRoute
  '/bet-history': typeof BetHistoryRoute
  '/casino': typeof CasinoRoute
  '/lottery': typeof LotteryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/slots': typeof SlotsRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRoute
  '/wallet': typeof WalletRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviator': typeof AviatorRoute
  '/bet-history': typeof BetHistoryRoute
  '/casino': typeof CasinoRoute
  '/lottery': typeof LotteryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/referral': typeof ReferralRoute
  '/slots': typeof SlotsRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRoute
  '/wallet': typeof WalletRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aviator'
    | '/bet-history'
    | '/casino'
    | '/lottery'
    | '/notifications'
    | '/profile'
    | '/promotions'
    | '/referral'
    | '/slots'
    | '/support'
    | '/updates'
    | '/wallet'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/messages'
    | '/admin/transactions'
    | '/admin/updates'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aviator'
    | '/bet-history'
    | '/casino'
    | '/lottery'
    | '/notifications'
    | '/profile'
    | '/promotions'
    | '/referral'
    | '/slots'
    | '/support'
    | '/updates'
    | '/wallet'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/messages'
    | '/admin/transactions'
    | '/admin/updates'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/aviator'
    | '/bet-history'
    | '/casino'
    | '/lottery'
    | '/notifications'
    | '/profile'
    | '/promotions'
    | '/referral'
    | '/slots'
    | '/support'
    | '/updates'
    | '/wallet'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/messages'
    | '/admin/transactions'
    | '/admin/updates'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AviatorRoute: typeof AviatorRoute
  BetHistoryRoute: typeof BetHistoryRoute
  CasinoRoute: typeof CasinoRoute
  LotteryRoute: typeof LotteryRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  ReferralRoute: typeof ReferralRoute
  SlotsRoute: typeof SlotsRoute
  SupportRoute: typeof SupportRoute
  UpdatesRoute: typeof UpdatesRoute
  WalletRoute: typeof WalletRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUpdatesRoute: typeof AdminUpdatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lottery': {
      id: '/lottery'
      path: '/lottery'
      fullPath: '/lottery'
      preLoaderRoute: typeof LotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-history': {
      id: '/bet-history'
      path: '/bet-history'
      fullPath: '/bet-history'
      preLoaderRoute: typeof BetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviator': {
      id: '/aviator'
      path: '/aviator'
      fullPath: '/aviator'
      preLoaderRoute: typeof AviatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates': {
      id: '/admin/updates'
      path: '/admin/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/admin/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AviatorRoute: AviatorRoute,
  BetHistoryRoute: BetHistoryRoute,
  CasinoRoute: CasinoRoute,
  LotteryRoute: LotteryRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  ReferralRoute: ReferralRoute,
  SlotsRoute: SlotsRoute,
  SupportRoute: SupportRoute,
  UpdatesRoute: UpdatesRoute,
  WalletRoute: WalletRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUpdatesRoute: AdminUpdatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
